# Generated by Django 4.2.2 on 2023-06-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0002_rename_nodes_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
