# Generated by Django 4.2.2 on 2023-06-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0003_edge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bubble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_bubble', to='bubble.edge')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_bubble', to='bubble.node')),
            ],
        ),
    ]
