# Generated by Django 4.2.2 on 2023-06-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0004_bubble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bubble',
            name='edge',
        ),
    ]
