# Generated by Django 4.2.2 on 2023-06-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0005_remove_bubble_edge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bubble',
        ),
    ]
