# Generated by Django 4.2.2 on 2023-06-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0006_delete_bubble'),
    ]

    operations = [
        migrations.CreateModel(
            name='BubbleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='edge',
            options={'verbose_name': 'Узлы', 'verbose_name_plural': 'Узлы'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'Ноды', 'verbose_name_plural': 'Ноды'},
        ),
    ]
