# Generated by Django 4.2.2 on 2023-06-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0007_bubblelist_alter_edge_options_alter_node_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='bubble_list',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bubble.bubblelist'),
            preserve_default=False,
        ),
    ]
