# Generated by Django 4.2.2 on 2023-06-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0008_node_bubble_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='bubble_list',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bubble.bubblelist'),
            preserve_default=False,
        ),
    ]
