# Generated by Django 4.2.2 on 2023-06-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0009_edge_bubble_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BubbleList',
            new_name='Canvas',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='bubble_list',
            new_name='canvas',
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
    ]
