# Generated by Django 4.2.2 on 2023-06-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0011_edge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='bubble.canvas'),
        ),
        migrations.AlterField(
            model_name='node',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='bubble.canvas'),
        ),
    ]
