# Generated by Django 4.2.2 on 2023-06-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0015_alter_datanode_options_alter_node_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='edge_id',
        ),
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
