# Generated by Django 4.2.2 on 2023-06-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0016_remove_edge_edge_id_alter_edge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='label',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='source',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='target',
        ),
        migrations.AlterField(
            model_name='edge',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_edges', to='bubble.canvas'),
        ),
        migrations.CreateModel(
            name='DataEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_data', to='bubble.edge')),
            ],
            options={
                'verbose_name': 'Данные для Ноды',
                'verbose_name_plural': 'Данные для Ноды',
            },
        ),
    ]
