# Generated by Django 4.2.2 on 2023-06-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0017_remove_edge_label_remove_edge_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataedge',
            options={'verbose_name': 'Данные для Узла', 'verbose_name_plural': 'Данные для Узла'},
        ),
        migrations.AddField(
            model_name='node',
            name='node_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
