# Generated by Django 4.2.2 on 2023-06-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0019_remove_node_node_id_alter_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='edge_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='node_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
