# Generated by Django 4.2.2 on 2023-06-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0020_edge_edge_id_node_node_id_alter_edge_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datanode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='canvas',
        ),
        migrations.RemoveField(
            model_name='positionnode',
            name='node',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='node_id',
            new_name='label',
        ),
        migrations.AddField(
            model_name='node',
            name='link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='posX',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='posY',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='style',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='DataEdge',
        ),
        migrations.DeleteModel(
            name='DataNode',
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='PositionNode',
        ),
    ]
